# Generated by Django 5.0.6 on 2026-06-01 08:49

import django.core.validators
from django.db import migrations, models


def backfill_open_timers(apps, schema_editor):
    """Pre-existing open timers (no end_time) were single-segment running timers."""
    TimeEntry = apps.get_model("tracker", "TimeEntry")
    TimeEntry.objects.filter(end_time__isnull=True).update(
        status="running",
        segment_started_at=models.F("start_time"),
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeentry',
            name='accumulated_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Worked minutes from completed segments (before the live one).'),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='segment_started_at',
            field=models.DateTimeField(blank=True, help_text='Start of the currently running segment; null while paused.', null=True),
        ),
        migrations.AddField(
            model_name='timeentry',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed')], default='completed', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(default='#0d6efd', help_text='Hex color (e.g. #0d6efd) used as a visual marker.', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a hex value like #0d6efd or #abc.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
        migrations.AlterField(
            model_name='timeentry',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Worked duration in minutes (excludes paused gaps).'),
        ),
        migrations.RunPython(backfill_open_timers, noop),
    ]
